openapi: 3.0.3
info:
  title: Schedule API
  description: API to retrieve a paginated list of schedules.
  version: 1.0.0
paths:
  /schedule/list:
    get:
      summary: Get a list of schedules
      description: Retrieve a paginated list of schedules with optional filters like `name` and `gender`.
      parameters:
        - name: page
          in: query
          required: true
          description: The page number to retrieve.
          schema:
            type: integer
            example: 1
        - name: item
          in: query
          required: true
          description: The number of items to retrieve per page.
          schema:
            type: integer
            example: 10
        - name: name
          in: query
          required: false
          description: Filter by name.
          schema:
            type: string
            example: "abcd"
        - name: gender
          in: query
          required: false
          description: Filter by gender.
          schema:
            type: string
            enum: [male, female, other]
            example: "male"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "abcd"
                        gender:
                          type: string
                          example: ""
                        profilePic:
                          type: string
                          format: uri
                          example: "https://example.com/profile.jpg"
                        age:
                          type: integer
                          example: 10
                  nextUrl:
                    type: string
                    format: uri
                    example: "<base_url>/schedule/list?page=2&item=10&name=abcd&gender=male"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters"

